- repo: https://github.com/ansible/ansible-lint.git
  sha: v4.1.0
  hooks:
    - id: ansible-lint
      files: \.(yaml|yml)$
      args: [--exclude=/Users/deekayen/.ansible]

- repo: https://github.com/willthames/ansible-review.git
  sha: v0.13.9
  hooks:
    - id: ansible-review
