---

language: python
cache: pip

env:
  - ANSIBLE_VERSION=2.8.15
  - ANSIBLE_VERSION=2.9.13
  - ANSIBLE_VERSION=latest

install:
  - if [ "${ANSIBLE_VERSION}" = "latest" ]; then pip3 install -U ansible; else pip3 install -U ansible==${ANSIBLE_VERSION}; fi
  - ansible-galaxy install --force git+https://github.com/deekayen/ansible-role-swiagent.git,${TRAVIS_COMMIT}
  - pip install ansible-lint

script:
  - ansible --version
  - ansible-lint --version
  - ansible-galaxy --version
  - ansible-lint -v .
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check -e 'ansible_python_interpreter=/usr/bin/python3'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
