---
- name: Validate role variables.
  ansible.builtin.import_tasks: assert.yml
  tags:
    - always

- name: "Debug: list configured Orion hosts."
  ansible.builtin.debug:
    var: orion_hosts
    verbosity: 3

- name: Set up the Orion repository for RedHat.
  when: ansible_facts.os_family == "RedHat"
  block:
    - name: Upload mirrorlist template for RedHat.
      ansible.builtin.template:
        src: mirrorlist.j2
        dest: /etc/yum.repos.d/swiagent-rhel-5.mirrors
        mode: "0644"
        owner: root
        group: root

    - name: Setup Orion repository for RedHat.
      ansible.builtin.yum_repository:
        name: swiagent
        description: SolarWinds Agent
        mirrorlist: file:///etc/yum.repos.d/swiagent-rhel-5.mirrors
        enabled: true
        gpgcheck: false

- name: Install perl to support monitoring extensions.
  ansible.builtin.package:
    name: perl
    state: present
  register: perl_install
  until: perl_install is succeeded
  retries: 2
  delay: 2

- name: "Debug: Results from installing perl."
  ansible.builtin.debug:
    var: perl_install
    verbosity: 3

- name: Copy agent configuration ini template.
  ansible.builtin.template:
    src: SolarWindsAgent.ini.j2
    dest: "{{ swiagentd_ini_file }}"
    mode: "0644"

- name: Install Solarwinds Agent.
  ansible.builtin.package:
    name: swiagent
    state: present
  register: swiagent_install
  retries: 2
  delay: 2
  until: swiagent_install is succeeded
  notify:
    - Initialize swiagentd.
    - Verify path ownership.
    - Start swiagentd.

- name: "Debug: Results from installing Solarwinds Agent."
  ansible.builtin.debug:
    var: swiagent_install
    verbosity: 3
