---

- name: init swiagentd
  command: "service swiagentd init \
            iniFile='{{ swiagentd_ini_file }}' \
            -recreateCert \
            -provision_passive \
            -is_active"
  warn: false
  tags:
  - skip_ansible_lint

- name: verify path ownership
  file:
    path: "{{ swiagent_install_path }}"
    owner: swiagent
    group: swiagent
    recurse: true

- name: start swiagentd
  service:
    name: swiagentd
    state: started
    enabled: yes
